!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 10, y: 0, z: 10}
      sizes:
      - !Vector3 {x: 5, y: 5, z: 5}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 30, y: 0, z: 30}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}

