!ArenaConfig
arenas:
  0: !Arena
    t: 0
    items:
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 2, y: 0, z: 2}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 2}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 2, y: 0, z: 38}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 2}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 38, y: 0, z: 2}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 2}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 38, y: 0, z: 38}
      sizes:
      - !Vector3 {x: 2, y: 1, z: 2}
