!ArenaConfig
arenas:
  0: !Arena
    t: 10000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 3, y: 3, z: 3}
    - !Item
      name: Wall
    - !Item
      name: Wall
    - !Item
      name: Wall
