!ArenaConfig
arenas:
  0: !Arena
    t: 500
    blackouts: [50, 55, 75, 80, 100, 105, 125]
    items:
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
