!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    blackouts: [-20]
    items:
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
    - !Item
      name: GoodGoal
    - !Item
      name: BadGoal
 
