!ArenaConfig
arenas:
  0: !Arena
    t: 100
    items:
    - !Item
      name: Agent
      positions:
        - !Vector3 {x: 20, y: 0.5, z: 10}
      rotations: [0]
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 2, y: 2, z: 2}
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 30}
    - !Item
      name: Wall
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      positions:
      - !Vector3 {x: 20, y: 0.5, z: 20}
      rotations: [0]
      sizes:
      - !Vector3 {x: 15, y: 5, z: 5}

